# Example configuration entry I2C
sensor:
  - platform: bmp280_i2c
    temperature:
      name: "${friendly_name} BMP280 Temperature"
      oversampling: 16x
      id: ${node_name}_bmp280_temperature
    pressure:
      name: "${friendly_name} BMP280 Pressure"
      id: ${node_name}_bmp280_pressure
    address: 0x76
    update_interval: 60s
  - platform: template
    name: "${friendly_name} Altitude"
    lambda: |-
      const float STANDARD_SEA_LEVEL_PRESSURE = 1013.25; //in hPa, see note
      return ((id(${node_name}_bmp280_temperature).state + 273.15) / 0.0065) *
        (powf((STANDARD_SEA_LEVEL_PRESSURE / id(${node_name}_bmp280_pressure).state), 0.190234) - 1); // in meter
    update_interval: 15s
    icon: 'mdi:signal'
    unit_of_measurement: 'm'
