
ld2410:

binary_sensor:
  - platform: ld2410
    has_target:
      name: ${node_name} Presence
      id: ${node_name}_presence
    has_moving_target:
      name: ${node_name} Moving Target
    has_still_target:
      name:  ${node_name} Still Target
    out_pin_presence_status:
      name: ${node_name} out pin presence status

    
sensor:
  - platform: ld2410
    light:
      name:  ${node_name} light
    moving_distance:
      name :  ${node_name} Moving Distance
    still_distance:
      name:  ${node_name} Still Distance
    moving_energy:
      name:  ${node_name} Move Energy
    still_energy:
      name:  ${node_name} Still Energy
    detection_distance:
      name:  ${node_name} Detection Distance
    g0:
      move_energy:
        name:  ${node_name} g0 move energy
      still_energy:
        name:  ${node_name} g0 still energy
    g1:
      move_energy:
        name:  ${node_name} g1 move energy
      still_energy:
        name:  ${node_name} g1 still energy
    g2:
      move_energy:
        name:  ${node_name} g2 move energy
      still_energy:
        name:  ${node_name} g2 still energy
    g3:
      move_energy:
        name:  ${node_name} g3 move energy
      still_energy:
        name:  ${node_name} g3 still energy
    g4:
      move_energy:
        name:  ${node_name} g4 move energy
      still_energy:
        name:  ${node_name} g4 still energy
    g5:
      move_energy:
        name:  ${node_name} g5 move energy
      still_energy:
        name:  ${node_name} g5 still energy
    g6:
      move_energy:
        name:  ${node_name} g6 move energy
      still_energy:
        name:  ${node_name} g6 still energy
    g7:
      move_energy:
        name:  ${node_name} g7 move energy
      still_energy:
        name:  ${node_name} g7 still energy
    g8:
      move_energy:
        name:  ${node_name} g8 move energy
      still_energy:
        name:  ${node_name} g8 still energy



switch:
  - platform: ld2410
    engineering_mode:
      name:  ${node_name} engineering mode
    bluetooth:
      name:  ${node_name} control bluetooth


number:
  - platform: ld2410
    timeout:
      name:  ${node_name} timeout
    light_threshold:
      name:  ${node_name} light threshold
    max_move_distance_gate:
      name:  ${node_name} max move distance gate
    max_still_distance_gate:
      name:  ${node_name} max still distance gate
    g0:
      move_threshold:
        name:  ${node_name} g0 move threshold
      still_threshold:
        name:  ${node_name} g0 still threshold
    g1:
      move_threshold:
        name:  ${node_name} g1 move threshold
      still_threshold:
        name:  ${node_name} g1 still threshold
    g2:
      move_threshold:
        name:  ${node_name} g2 move threshold
      still_threshold:
        name:  ${node_name} g2 still threshold
    g3:
      move_threshold:
        name:  ${node_name} g3 move threshold
      still_threshold:
        name:  ${node_name} g3 still threshold
    g4:
      move_threshold:
        name:  ${node_name} g4 move threshold
      still_threshold:
        name:  ${node_name} g4 still threshold
    g5:
      move_threshold:
        name:  ${node_name} g5 move threshold
      still_threshold:
        name:  ${node_name} g5 still threshold
    g6:
      move_threshold:
        name:  ${node_name} g6 move threshold
      still_threshold:
        name:  ${node_name} g6 still threshold
    g7:
      move_threshold:
        name:  ${node_name} g7 move threshold
      still_threshold:
        name:  ${node_name} g7 still threshold
    g8:
      move_threshold:
        name:  ${node_name} g8 move threshold
      still_threshold:
        name:  ${node_name} g8 still threshold


button:
  - platform: ld2410
    factory_reset:
      name:  ${node_name} factory reset
    restart:
      name:  ${node_name} restart
    query_params:
      name:  ${node_name} query params


text_sensor:
  - platform: ld2410
    version:
      name:  ${node_name} firmware version
    mac_address:
      name:  ${node_name} mac address


select:
  - platform: ld2410
    distance_resolution:
      name:  ${node_name} distance resolution
    baud_rate:
      name:  ${node_name} baud rate
    light_function:
      name:  ${node_name} light function
    out_pin_level:
      name:  ${node_name} out pin level      