i2s_audio:
  - id: i2s_in
    i2s_lrclk_pin: GPIO16
    i2s_bclk_pin: GPIO17
  - id: i2s_out
    i2s_lrclk_pin: GPIO18
    i2s_bclk_pin: GPIO21

media_player:
  - platform: i2s_audio
    i2s_audio_id: i2s_out
    name: assistmediaplayer
    id: big_speaker
    dac_type: external
    i2s_dout_pin: GPIO15 ##ampli DIN
    mode: stereo
