esphome:
  name: $node_name
  friendly_name: $friendly_name
  min_version: 2024.11.0
  name_add_mac_suffix: false
  platformio_options:
    build_flags: "-DBOARD_HAS_PSRAM"
    board_build.arduino.memory_type: qio_opi
#    board_build.partitions: large_spiffs_16MB.csv
    board_build.flash_mode: dio


esp32:  
  board: esp32-s3-devkitc-1
  framework:
    type: arduino
   
psram:
  mode: octal
  speed: 80MHz

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key
  reboot_timeout: 1h

# Allow Over-The-Air updates
ota:
- platform: esphome
  password: !secret ota_password

# Disable for Ethernet

#wifi:
#  ssid: !secret wifi_ssid
#  password: !secret wifi_password

# Disabled for testing

#bluetooth_proxy:
 # active: true


ethernet:
  type: W5500
  clk_pin: GPIO13
  mosi_pin: GPIO11
  miso_pin: GPIO12
  cs_pin: GPIO14
  interrupt_pin: GPIO10
  reset_pin: GPIO9

i2c:
  sda: GPIO42
  scl: GPIO41
  scan: true
  id: bus_a
  
uart:
  tx_pin: GPIO47
  rx_pin: GPIO48
  baud_rate: 256000
  
binary_sensor:
  - platform: status
    name: ${friendly_name} Status
    
switch:
  - platform: restart
    name: ${friendly_name} Restart